// const fs=require('fs')
// fs.writeFileSync('notes.txt','This file was created by Node.js!')
// fs.appendFileSync('notes.txt','This is the appended text.')

// const name=require('./utils.js')
// console.log('app.js is running')
// console.log(name(2,3))
const validator=require('validator')
const getNotes=require('./notes.js')
console.log(getNotes())
console.log(validator.isEmail('bharattulsani21@gmail.com'))
console.log(validator.isURL('bharattulsani21@gmail.com'))